### ISSUE TITLE
convertFile ok, loadFile+convert undefined method 'rindex'

### ISSUE THREAD

**Issue by amengcs** [asciidoctor/asciidoctorj#1039]
Using versions:

  implementation 'org.asciidoctor:asciidoctorj:2.5.1'
  implementation 'org.asciidoctor:asciidoctorj-pdf:1.5.4'
  implementation 'org.asciidoctor:asciidoctorj-diagram:2.1.2'

 Given:

   File document
  OptionsBuilder ob

This works ok:

asciidoctor.convertFile(document, ob.build());

But, what I thought to be equivalent separate invocations of loadFile and convert, generates an Exception:

    Document ast = asciidoctor.loadFile(document, ob.build());
    ast.convert();

Failed to load AsciiDoc document - undefined method `rindex' for true:TrueClass
	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:103) ~[na:na]
	at RUBY.load_file(uri:classloader:/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:115) ~[na:na]
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1158) ~[jruby-core-9.2.17.0.jar!/:na]
	at RUBY.load_file(uri:classloader:/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:115) ~[na:na]

**Comment by mojavelinux** [comment]
Using two separate calls isn't exactly the same, but I don't expect it to fail. Unfortunately, I can't see where the real error is coming from since this stacktrace is truncated. Please share the whole stacktrace. Also, sharing a reproducible example would help us to be able to debug.

**Comment by amengcs** [comment]
That really is all of the stack trace that I saw as both gradle output and in my log file.
 Not sure why  it is truncated or what is truncating it.

Here is a github project which demonstrates the issue factored out of my larger SpringBoot app into a single plain Java class.

https://github.com/amengcs/p1039

Throws the missing method "rindex" exception during loadFile method invocation.
Execute with "./gradlew run".

As always, thanks for the whole Asciidoctor ecosystem.  One of those great tools that I use over and over wherever I go and year after year!

BTW: I think loadFile with Options as a parameter is a new method form in version 2.5.1.

Let me know if you need any additional info.

**Comment by abelsromero** [comment]
The issue happens when set `to_file` option to `true`.
I could also reproduce in Ruby with a simple file
```
require 'asciidoctor'

Asciidoctor.load("= p1039", to_file: true)
```

The exact line does not match with main branch, but I suspect the line is this one (1 line off) https://github.com/asciidoctor/asciidoctor/blob/a0bc2fbd4cf05c626824a1b3074d7f8812b130b4/lib/asciidoctor/helpers.rb#L228

**Comment by mojavelinux** [comment]
Thanks for tracking that down, @abelsromero. That does indeed look like a bug in core (and it could be related to https://github.com/asciidoctor/asciidoctor/issues/2435). Could you file an issue for this? (I'd like to make it a separate issue since we want to fix the crash separately from adding support for the to_file option when used this way).

**Comment by abelsromero** [comment]
Done https://github.com/asciidoctor/asciidoctor/issues/4055, and merit goes to @amengcs and the reproducer provided. It was just a matter of enabling options one by one.
