### ISSUE TITLE
Question: null-backend

### ISSUE THREAD

**Issue by OlegKunitsyn** [asciidoctor/asciidoctorj#1095]
`Document document = asciidoctor.load(asciidoc, Options.builder().backend.build());` converts asciidoc to html by default. Is it possible to walk through the original AST?

**Comment by abelsromero** [comment]
What version are you using? `load` should not convert anything, it should run everything (including extensions) and omit the output.

Regarding how to explore the AST you are already on the right track but the AST representation is not simple, here's an example to get you started https://github.com/abelsromero/asciidoctorj-experiments/blob/6ea57e982ca62539bd7836e3f6e0d79fed282f17/src/main/java/org/asciidoctor/demos/AstTraverser.java#L18-L31. But there are a few quircks you may find.

What is the final goal?

**Comment by OlegKunitsyn** [comment]
Thank you for the answer. My asciidoctorj 2.5.4
```
Asciidoctor asciidoctor = Asciidoctor.Factory.create();
Document document = asciidoctor.load("== First Chapter", Options.builder().backend(null).build());
System.out.println(document.getContent());

<div class="sect1">
<h2 id="_first_chapter">First Chapter</h2>
<div class="sectionbody">

</div>
</div>
```
I expect `== First Chapter` on `backend(null)` instead of html. 
Your suggestion with Treeprocessor is interesting, but NodesTraverser received converted document, too:
```
Asciidoctor asciidoctor = Asciidoctor.Factory.create();
asciidoctor.javaExtensionRegistry().treeprocessor(new Treeprocessor() {
    @Override
    public Document process(Document document) {
        System.out.println(document.getContent());
        new NodesTraverser().processNode(document, 0);
        return document;
    }
});
Document document = asciidoctor.load("== First Chapter", Options.builder().backend(null).build());

<div class="sect1">
<h2 id="_first_chapter">First Chapter</h2>
<div class="sectionbody">

</div>
</div>
[info] document (DocumentImpl)				 context: document				 style: null				 level: 0
[info]     section (SectionImpl)				 context: section				 style: null				 level: 1
```

**Comment by OlegKunitsyn** [comment]
The final goal is the styled asciidoc i.e. `<span class="h2">== First Chapter</span>`

**Comment by abelsromero** [comment]
> I expect `== First Chapter` on `backend(null)` instead of html.

What you see is the expected behaviour. html is the default backed if nothing or null is set. And `getContent` returns the converted content, since html is the default, you see that html when calling it.
You should not be retriving content if you want to explore the AST.

> Your suggestion with Treeprocessor is interesting, but NodesTraverser received converted document, too:

The useful part is `NodesTraverser` class, the example shows both usages; directly with the result of load, or from extensions/converters.
Inside it you see how to traverse the AST using `getBlocks()` recursively. Then you can check the instanceof of each node to treat them taking care of the specifics of each one.
![image](https://user-images.githubusercontent.com/5781153/173249069-b728c912-46e1-4e00-8cbe-045d52340914.png)

**Comment by mojavelinux** [comment]
And if you wanted just the section title converted, then you would need something like:

```
Section sect = doc.getSections()[0]
System.out.println(sect.getTitle());
```

There is no such thing as a null backend. Asciidoctor is always converting to something. But by loading the document, you can pause before conversion, walk the document, and pull out information from it that you are interested in. If you were to call `doc.getContent()`, that would defeat the whole purpose since you are asking the processor to convert the whole document to HTML.

**Comment by mojavelinux** [comment]
Questions like this should be directed to the project chat rather than the issue tracker. In the project chat, we can have a more open-ended discussion. https://chat.asciidoctor.org.

**Comment by abelsromero** [comment]
@OlegKunitsyn maybe you'll be interested in https://github.com/asciidoctor/asciidoctor-reducer then, if you can includes and substitutions and you want the final value, you may want to parse the reduced version. Here is a bit of context and history https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/.E2.9C.94.20Asciidoctor.20reducer.20.28was.20AsciiDoc.20coalescer.29.
