### ISSUE TITLE
Identity backend

### ISSUE THREAD

**Issue by d-gregorczyk** [asciidoctor/asciidoctorj#1104]
Hi folks,

I'm poking  around with the asciidoctorj lib and try to read an adoc file just to perform some transformation on the source and write it back to an adoc file again. Is there any identity-backend available?

Thx,
David

**Comment by mojavelinux** [comment]
What is the said transformation?

**Comment by d-gregorczyk** [comment]
I'm essentially reading in an adoc file by using AsciidoctorJ having a block processor extension that analyzes and changes some contents. The resulting output however is neither PDF nor HTML, it is supposed to be the transformed Asciidoc code. Reason is, that I try to run a multipage HTML converter that cannot be integrated with AsciidoctorJ, so I need AsciiDoc text again.

The question is: is there any means to attach a backend that processes pre processor, block processor extensions etc. and just transforms from AsciiDoc into AsciiDoc, like

```
= Foo

== Bar

[my_block#r100]
.R100
--
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

- B1
- B2

TIP: They can contain any type of content.
--
```
into
```
= Foo

== Bar

[my_block#r100]
.R100
--
Sidebars are used to visually separate auxiliary bits of content
that supplement the main text.

- B1
- B2

TIP: They can contain any type of content.
--
```
?

Thanks for your help!

**Comment by mojavelinux** [comment]
There's a tool that does something close to what you want. That tool is [Asciidoctor Reducer](https://github.com/asciidoctor/asciidoctor-reducer). What it does is interpret preprocessor directives (includes and conditionals). What it doesn't do from your list is process block extensions.

In theory, yes, it is possible to write a converter that generates AsciiDoc. It would look very similar to the manpage converter (which also produces a text-based format). However, what I prefer to do in this case is to use the sourcemap to find out the location of blocks, then use line replacement based on that information to perform surgery on the document.

General questions like this are best directed to the project chat at https://chat.asciidoctor.org rather than the issue tracker.

**Comment by d-gregorczyk** [comment]
Thanks for you reply! Going to do that next time.
