### ISSUE TITLE
Missing `toc-title` attribute in org.asciidoctor.Attributes

### ISSUE THREAD

**Issue by eastack** [asciidoctor/asciidoctorj#1131]
There is no `toc-title` attribute in org.asciidoctor.Attributes. How should I set this attribute? Other methods using map configuration are already deprecated.

**Comment by abelsromero** [comment]
You can use `attribute` from the builder
https://github.com/asciidoctor/asciidoctorj/blob/c5aa7f2b8c5a3999f2d12604dddb189f2fbf273c/asciidoctorj-api/src/main/java/org/asciidoctor/AttributesBuilder.java#L432

or https://github.com/asciidoctor/asciidoctorj/blob/c5aa7f2b8c5a3999f2d12604dddb189f2fbf273c/asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java#L592 from `Attribute`, but beware of the empty value for attributes like this one. That's why I'd recommend the Builder.

**Comment by eastack** [comment]
Thank you so much for your help!
