### ISSUE TITLE
Bundle the pygments.rb gem

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#123]
Bundle the pygments.rb gem so that the pygments source-highlighter can be used.

We should add a note that the pygmentize command must be available on the system in order for the pygments.rb library to function.

**Comment by fap-** [comment]
@mojavelinux Shouldn't pygments.rb work now after your PR got accepted? I'm trying to use it with the asciidoctor-gradle plugin but I'm getting an error. Not sure what the problem is.
`Could not list contents of '/home/fap/repos/com.vogella.tutorials.scripts/Android/build/jruby_prepare/gems/pygments.rb-1.1.1/vendor/pygments-main/scripts/find_error.py'. Couldn't follow symbolic link.`

**Comment by mojavelinux** [comment]
Yes, that is correct, it should now work.

However, it turns out when the team published the new gem, they included a broken symlink in the package which breaks loading. I've opened an issue. See https://github.com/tmm1/pygments.rb/issues/176.

Having said that, I think the right path forward in turns of bundling is a switch to Rouge. It's good that Pygments is now an option, but it should not be the one we provide out of the box because the IPC is inherently slow. Rouge is a port / emulated version of Pygments for Ruby and looks to be our future at this point.
