### ISSUE TITLE
Invalid 'backend' attribute

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1260]
There are methods to set `backend` as an attribute in [AttributesBuilder](https://github.com/asciidoctor/asciidoctorj/blob/a03c403db184d9a8b5c74f867f3c74cb421d1bfa/asciidoctorj-api/src/main/java/org/asciidoctor/AttributesBuilder.java#L131) and [Attributes](https://github.com/asciidoctor/asciidoctorj/blob/a03c403db184d9a8b5c74f867f3c74cb421d1bfa/asciidoctorj-api/src/main/java/org/asciidoctor/Attributes.java#L138).

Unless I missed something this seems to be some mistake and should be deleted. Does anyone know of an actual use for that?

**Comment by robertpanzer** [comment]
I added this because Asciidoctor itself also stores this as an attribute:
https://github.com/asciidoctor/asciidoctor/blob/182b43ee445fdbb901941effe90e4e2247487489/lib/asciidoctor/cli/options.rb#L53
Since asciidoctorj-cli also has to pass it in an attribute to Asciidoctor, I'd personally say that it is ok to have it in Attributes.

**Comment by abelsromero** [comment]
OK, I am not going to deny it's weird but I see it's referred to in the official docs also https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/#intrinsic-attributes.
