### ISSUE TITLE
Not being able to replace an attribute with a Preprocessor

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#274]
While testing the extensions I found this case which a bit odd to me.
I have a document starting with

```
Document Title
==============
:author: asciidoctor-maven-plugin
Yada yada yada

 . . .
_Created by {author}_

```

Then I wrotte a simple Preprocessor following the example in the documentation with the following code:
```
    public PreprocessorReader process(Document document, PreprocessorReader reader) {
        String author = (String)document.getAttributes().get("author"); <1>
        document.getAttributes().put("author", "Abel");                          <2>
        author = (String)document.getAttributes().get("author");           <3>
        return reader;
    }
```

The thing is that when I debug I see the following behaviour:
* After 1, author is always null
* After 3, author is always "Abel"
If `:author:` declaration is present, in the rendered HTML the value at the end is not replaced by "Abel". However, if I remove the line `:author: asciidoctor-maven-plugin` from the AsciiDoc source, the value of the attribute is replaced and Abel appears in the HTML.

I remember some time ago an issue with attributes like toc not being set, is it related to it? or should I use another kind of processor?

**Comment by mojavelinux** [comment]
This problem is coming up in several places. @nerk was also having this problem when using the JavaScript API. The long and short of it was that the API didn't take this into account when it was designed, so we need to go back and add proper support for it. The attributes get restored when switching between phases and it overwrites changes made externally.

Related issues are:

* https://github.com/asciidoctor/asciidoctor/issues/1255
* https://github.com/asciidoctor/asciidoctor.js/issues/95

**Comment by abelsromero** [comment]
I knew I've seen it before. Thanks for the explanation, you can close this issue if you want.
