### ISSUE TITLE
Adding an AsciiDoc DocumentBuilder

### ISSUE THREAD

**Issue by RobWin** [asciidoctor/asciidoctorj#281]
Hello,

I developed a first version of an AsciiDoc (and Markdown) DocumentBuilder. The primary goal of this project is to simplify the creation of an AsciiDoc document via the Builder pattern.

[markup-document-builder] (https://github.com/RobWin/markup-document-builder)

The library does not support the full AsciiDoc features yet, because I tried to create a Mardown and AsciiDoc builder. What about adding a DocumentBuilder into asciidoctorj directly?

I use the library in [swagger2markup] (https://github.com/RobWin/swagger2markup)

Kind regards,
Robert Winkler

**Comment by mojavelinux** [comment]
I definitely like the idea of having an AsciiDoc markup builder in AsciidoctorJ. However, right now we're having the problem that we need to refactor some of the packages to tighten things up a bit, particularly around the AST model. It would be best to drop this in after those changes are made. (Robert is driving the effort to work through those changes ). 

I do have one question (without diving deep into the markup builder). Are you building an AST of the document in the builder than converting it to AsciiDoc in a follow-up step? If so, would it be possible to have the builder use the AST in AsciidoctorJ? Ideally we want everything to go through Asciidoctor's model when parsing and writing AsciiDoc. That way, we always have an intermediary structure to work with. It would also make sense if the writer is an AsciiDoc converter, again so we stay within the model.

If you'd rather not use Asciidoctor's model, then I think the document builder should remain a separate project. Otherwise, we end up with multiple ways to work with documents in the same code base which is a bit of the problem we have now.

Overall, I'm really excited about this effort! Being able to build up an AsciiDoc document programmatically is a very powerful tool, especially for reporting engines / tools!

**Comment by lordofthejars** [comment]
What I see with this is something like javaparrot project but for AsciiDoc,
and it would be really useful for extensions/converters and for external
tools
El dc., 1 d’abr., 2015 a les 20.59 Dan Allen <notifications@github.com> va
escriure:

**Comment by RobWin** [comment]
Thx for the long comment.
No I'm not using any AST yet. I'm going to have a look at Asciidoctor's model.

**Comment by RobWin** [comment]
Do you make advertisingfor projects that use AsciiDoc and AsciiDoctorJ in twitter?
I want to propgate the use of AsciiDoc to document APIs.

See https://github.com/RobWin/swagger2markup

**Comment by lordofthejars** [comment]
Well everything that is tag gee with @asciidoctor or #asciidoctor is always
retweeted
El dl., 20 d’abr., 2015 a les 21.56 Robert Winkler <notifications@github.com>
va escriure:

**Comment by RobWin** [comment]
ok. Thx. Shall I close the issue?

**Comment by RobWin** [comment]
I had a look at the AST. I think a Java-based AsciiDoc Builder should be free of JRuby dependencies. Especially if Java framework libraries want to use them. AsciiDoctorJ was refused by springfox because of its JRuby dependency. Swagger had initially the same problems because of its Scala dependency. Now they are almost Scala free and Swagger is finally an option for MicroServices.

**Comment by mojavelinux** [comment]
>  I think a Java-based AsciiDoc Builder should be free of JRuby dependencies. 

I agree there should definitely be an option of having a builder that doesn't have JRuby dependencies. Ideally we want the AST in AsciidoctorJ to be free of JRuby references as well, but it's a work in progress. It certainly shouldn't hold up the creation of a pure Java library for producing AsciiDoc, so I'm glad you've been working on one. More options means more exploration, and that's a good thing.

**Comment by mojavelinux** [comment]
Btw, we can promote your effort on the asciidoctor.org docs page. We are doing a bit of reorganization of it right now, but we have a new page coming for extensions and add-ons in the ecosystem. I think this would be a good place for the mention. See https://github.com/asciidoctor/asciidoctor.org/pull/372

**Comment by RobWin** [comment]
Thx for your reply. 
Yes. it would be great to have an add-ons page. 
But my builder is still very limited, because it was specifically built for swagger2markup.
