### ISSUE TITLE
Font-Awesome integration, works?

### ISSUE THREAD

**Issue by gitblit** [asciidoctor/asciidoctorj#381]
This is example html generated when using the Font-Awesome images constant.

```html
<td class="icon">
  <i class="fa icon-tip" title="Tip"></i>
</td>
```

`fa icon-tip` is not a valid Font-Awesome reference.  The Font-Awesome naming scheme is `fa fa-something`.  Am I missing something with using the Font-Awesome integration?

**Comment by LightGuard** [comment]
Which version of asciidoctor are you using? Unless font-awesome has changed
their scheme again in the past year it should be fine.

On Wed, Aug 26, 2015 at 1:18 PM, James Moger <notifications@github.com>
wrote:

> This is example html generated when using the Font-Awesome images constant.
>
> <td class="icon">
>   <i class="fa icon-tip" title="Tip"></i>
> </td>
>
> fa icon-tip is not a valid Font-Awesome reference. The Font-Awesome
> naming scheme is fa fa-something. Am I missing something with using the
> Font-Awesome integration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctorj/issues/381>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by abelsromero** [comment]
Hi,

From what i've seen adminition blocs use `icon-something`, icons using the macro `icon:something[]` use `fa-something`.
I am not familiarized in the way that Font Awesome works under the hood and I cannot answer about how the CSS styles are used. But regarding the title question font awesome integration does work.

From what I see, your example comes from an admonition block like this one:
```
TIP: Tips are cool, they improve readability and ensure the reader don't miss anything important.
```

If the issue is that the icons don't show, keep in mind you must pass the attribute "icons=font" to the converter.
I presume you are using directly AsciidoctorJ, in that case, you can use the helper class `AttributesBuilder` ([see icons method](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/AttributesBuilder.java#L359)) passing the the [FONT_ICONS  constant](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/Attributes.java#L40).

If you're using another kind of integration like maven or gradle, please let us know.

**Comment by mojavelinux** [comment]
We use a custom CSS class for admonition icons. That's because we have a layer of abstraction between the icon name and the Font Awesome character it maps to.

You need a small amount of CSS from the default stylesheet to make this mapping if you are not using the default stylesheet.

See https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css#L348-L354

**Comment by mojavelinux** [comment]
To provide a little bit more insight, we didn't want to hard-code the choice of icon for admonition blocks from the Font Awesome palette. The CSS makes that connection.

**Comment by gitblit** [comment]
Perfect.  Thanks @mojavelinux, the CSS was what I was missing.

Yes, @abelsromero I am using the library directly.  The FONTS constant you refer to results in the html I posted in the description.  The missing piece is the excerpt from the stylesheet.
