### ISSUE TITLE
Images don't work when using imagesdir in EPUB version

### ISSUE THREAD

**Issue by mraible** [asciidoctor/asciidoctorj#388]
I'm trying to compile an Asciidoctor book to HTML, PDF and EPUB. I've spent the last couple of hours trying to get images to show up in the EPUB document with mixed results. It seems like the EPUB conversion does not honor the "imagesdir" attribute, while the HTML and PDF versions do. 

My project is based off of asciidoctor-gradle-examples/asciidoc-to-all-example. Here's what my `src/main/asciidoc` folder looks like:

````
├── chapters
│   ├── about.adoc
│   ├── chapter2.adoc
│   ├── dedication.adoc
│   ├── introduction.adoc
│   └── preface.adoc
├── favicon.ico
├── images
│   ├── about
│   │   ├── *.png
│   ├── chapter2
│   │   ├── *.png
│   └── cover.png
└── index.adoc
````

I have an image in chapters/about.adoc that I've been experimenting with. Here's its path:

image::images/about/foo.jpg

In build.gradle, I have `'imagesdir': './',` and it works with HTML and PDF. 

Here's what I've found when trying to get this image to render in all three formats:

* No imagedir in build.gradle and `:imagesdir:` in index.adoc - works in HTML and PDF
* If I use `'imagesdir': './images'`, in build.gradle, it causes icons to work in epub - otherwise they do not
* No image dir in build.gradle and no imagedir in index.adoc - works in HTML and PDF, no images in epub
* If I move images to the `chapters` directory, no imagedir defined - no images in HTML/PDF, no images, but images do work in epub

Based on the last couple hours of trying to get this to work, it seems like EPUB only works for embedding images when you use a path directly to the images and don't define an `imagesdir`. _However_, if you want the default icons to show up in the EPUB document, you have to define imagesdir as `./images` in the build.gradle.

Is it possible to embed images in *.adoc files and have them render properly in all three formats?

My dependencies:

````
    dependencies {
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.8'
        classpath 'com.bluepapa32:gradle-watch-plugin:0.1.5'
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.2'
        classpath 'org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.4'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.9'
    }

asciidoctorj {
    version = '1.5.2'
}
````

**Comment by mojavelinux** [comment]
The `imagesdir` is very restrictive at the moment in the EPUB3 converter. It was programmed to work in a very specific setup and not for the general use case. This is one of the (many) reasons the EPUB3 converter is still in alpha.

Since this issue is specific to the EPUB3 converter, it probably belongs in the asciidoctor-epub3 repository. AsciidoctorJ simply delegates to that converter. It's probably related to the following issue: https://github.com/asciidoctor/asciidoctor-epub3/issues/22

In general, `imagesdir` is a common source of confusion because we're trying to use a single attribute to address different scenarios with very different needs. It's this experience that is going to help guide us to the right approach.

One way to solve the issue is to set the imagesdir depending on the backend. You can use a conditional either in the Gradle build or by doing something in the AsciiDoc like:

```
ifdef::backend-epub3[:imagesdir: <value>]
ifdef::backend-pdf[:imagesdir: <value>]
ifndef::imagesdir[:imagesdir: <value.]
```

**Comment by mraible** [comment]
I figured out a solution.

1. In build.gradle, I set imagedir to `'./images'`
2. I removed the `imagesdir` setting from `index.adoc`
3. I changed all image paths from `image::images/foo` to `image::foo`
4. I created a symlink in `src/docs/asciidoctor/chapters` to `src/docs/asciidoc/images`

As a sidenote, I noticed that org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.9 fails to generate PDF and EPUB, but org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.8 works just fine.

**Comment by robertpanzer** [comment]
@mraible You're ok to close this issue and possibly open a new issue in asciidoctor/asciidoctor-epub?

**Comment by mraible** [comment]
Yes. I believe this issue in asciidoctor-epub3 is the same thing:

https://github.com/asciidoctor/asciidoctor-epub3/issues/22

**Comment by mojavelinux** [comment]
I agree with all the settings except (1). The path should be 'images' instead of './images'. Otherwise, the EPUB3 packager writes a `/./` segment in the manifest, which is problematic for some viewers. Since these are effectively the same path, it's safe to drop the leading `./`.

I'd definitely like to be able to get it to work with out a symlink. We'll call that a goal.
