### ISSUE TITLE
Include URI doesn't work since 1.5.4

### ISSUE THREAD

**Issue by bclozel** [asciidoctor/asciidoctorj#460]
The `"include::http://example.org/document.adoc[]"` feature does not work since version 1.5.4 (and was previously working in 1.5.3.

I've created a small repro project to demonstrate that: https://gist.github.com/bclozel/9efef280e8ac43f222f28deabea517a1

Let me know if I've missed something in my repro/configuration.

**Comment by robertpanzer** [comment]
Hi Brian,

I think the safe mode is set too strict (SAFE!)
If it worked with 1.5.3 this seems more like a bug in 1.5.3.
As this issue is more related to Asciidoctor (Asciidoctorj just forwards
the calls) maybe @mojavelinux can shed some light on this.

Does it work if you set the safe mode to UNSAFE?

Cheers Robert

Am Sonntag, 8. Mai 2016 schrieb Brian Clozel :

**Comment by bclozel** [comment]
Hi Robert,

Indeed it was working previously in SAFE mode, but still doesn't work when changed to UNSAFE.
Also, changing the URL to "http" (just in case it's related to JRuby + SSL) still shows the issue.

**Comment by mojavelinux** [comment]
This stems from a bug not in Asciidoctor or AsciidoctorJ, but rather JRuby. The default version of JRuby changed between 1.5.3 and 1.5.4. It moved from 1.7.22 to 1.7.21 to address issues with running on Windows. Unfortunately, 1.7.21 is known to have problems reading from URLs. Therefore, this can be fixed by setting the version of JRuby explicitly.

```xml
<dependency>
    <groupId>org.jruby</groupId>
    <artifactId>jruby-complete</artifactId>
    <version>1.7.22</version>
</dependency>
```

There are numerous issues with JRuby 1.7, esp on Windows (as we know all too well), so what we really encourage you to do is start testing with JRuby 9k.

```xml
<dependency>
    <groupId>org.jruby</groupId>
    <artifactId>jruby-complete</artifactId>
    <version>9.0.5.0</version>
</dependency>
```

JRuby has matured a lot over the last few years and we'll start to benefit from that maturity as users migrate to JRuby 9k.

**Comment by mojavelinux** [comment]
I describe this problem in detail in the following issue. https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/153#issuecomment-99280861

I should clarify that the problem has to do with reading from a URL with JRuby 1.7 when JRuby is running in 2.0 mode. The problem only happens with certain versions of JRuby 1.7, which is why you see a difference between using AsciidoctorJ 1.5.3 and 1.5.4.

**Comment by bclozel** [comment]
Thanks!
