### ISSUE TITLE
configure travis to run only the check task for PR's

### ISSUE THREAD

**Issue by ancho** [asciidoctor/asciidoctorj#483]
Currently every PR seems to fail on travis. In reality the check task is successful. But the `bash test-asciidoctor-upstream.sh` tasks fails.

See https://travis-ci.org/asciidoctor/asciidoctorj/jobs/144690217

Is it necessary to run the bash script for a pull request?

**Comment by mojavelinux** [comment]
Ideally, yes. It ensures that AsciidoctorJ and Asciidoctor core never get out of sync. It appears that at some point this script broke. We need to address that because this is a very important check.

I don't think it's necessary to run this script for every job in the matrix. It only needs to be run for one of the the JDKs.

**Comment by mojavelinux** [comment]
Aha, I can see why. The .gemspec in Asciidoctor core changed and our patch no longer applies cleanly. So, in effect, this script has done its job. We are failing against the upstream right now. I'll try to fix it.

**Comment by mojavelinux** [comment]
I can see what's happening. This shouldn't be too hard to fix.

**Comment by mojavelinux** [comment]
@ancho wdyt? We now run the upstream test against the first job in the build for PRs and all jobs in the build when we merge to master. Sound reasonable?

**Comment by ancho** [comment]
:+1: Makes sense ;) Good job!
