### ISSUE TITLE
Setting options when using AsciidoctorInvoker

### ISSUE THREAD

**Issue by kduske-n4** [asciidoctor/asciidoctorj#508]
My goal is to add line numbers to the error messages produced by my custom macro processors. Unless I missed something, I have to set the `:sourcemap` option when converting a document to get line numbers from the nodes.

I currently rely on AsciidoctorInvoker when calling AsciidoctorJ from the command line. There seems to be no way of setting that particular option (and many others) when using AsciidoctorInvoker. I would rather not resort writing my own CLI for AsciidoctorJ, so it would be great to be able to set all options using AsciidoctorInvoker.

**Comment by mojavelinux** [comment]
> I have to set the :sourcemap option when converting a document to get line numbers from the nodes.

Correct.

Currently, there is no way to specify this option on the CLI. However, I don't think that's the right place to enable it because it's not up to the client to turn on a low-level feature that an extension needs. Instead, it should be possible for a Preprocessor to turn on the sourcemap option on the Document object. For that to happen, we need to first make sourcemap read/write in core. Then, AsciidoctorJ can expose a getter/setter for this option. Technically, AsciidoctorJ can make that change now...it would just require using the low-level `instance_variable_set` method to assign the value. I'll proceed with the enhancement in core in the meantime.

**Comment by mojavelinux** [comment]
Proposed API:

```
Document#getSourcemap()
Document#setSourcemap(boolean state)
```

(There doesn't seem to be consensus about whether sourcemap is one word or two).

**Comment by kduske-n4** [comment]
@mojavelinux thanks! I have added some code to AsciidoctorJ to enable sourcemaps via the CLI, but you are right, it should not be up to the client in general (even though in our case it would be okay). I'll wait for your changes instead.

**Comment by robertpanzer** [comment]
Hi,

I just had a look at the sources of Asciidoctor on this, and without trying yet I cannot imagine that it’ll work to set the sourcemap property on the Document.

The creation of the Document, evaluation of the sourcemap option and parsing of the content (which makes the Parser set the source_location) is all encapsulated in the method Asciidoctor#load.
There is currently no hook(*) in Asciidoctor that could be used by AsciidoctorJ to hook in between Document creation and parsing to set this property.

(*) Well, I could set the option parse to false and then invoke the parsing manually, but I don’t think that I want to do that.

Or am I missing something?

Cheers
Robert

**Comment by mojavelinux** [comment]
The sourcemap setting is an option just like `:header_footer`, `:to_file`, `:attributes`, `:backend`, `:safe`, etc. Just set the value to `true` and the sourcemap will be enabled.

Here's how it looks in Ruby.

```ruby
doc = Asciidoctor.load 'AsciiDoc source', sourcemap: true
```

**Comment by mojavelinux** [comment]
Oh, and if you want to enable it from an extension, here's how it's done:

```
Asciidoctor::Extensions.register do
  preprocessor do
    process do |doc, reader|
      doc.sourcemap = true
      nil
    end
  end
end
```

It's true that `setSourcemap(true)` on Document would only have an effect if it gets called from a preprocessor (before the document is parsed). Otherwise, it would be called too late. So it is a somewhat odd option in that regard.

**Comment by mojavelinux** [comment]
I don't think AsciidoctorJ has to care about the details. Just pass the request to set the sourcemap to the underlying Document object in Ruby.

**Comment by mojavelinux** [comment]
I've submitted PR #693 with a proof of concept, but it lacks tests at the moment.
