### ISSUE TITLE
pdfmarks file is not generated with latest asciidoctor maven plugin.

### ISSUE THREAD

**Issue by saravankrish** [asciidoctor/asciidoctorj#520]
I compile hbase (master branch) with latest asciidoctor-maven-plugin (V1.5.3) and askciidoctorj-pdf (V1.5.0-alpha.11) and I get below error. Please help me resolve this issue.

OS: CentOS release 6.6
Maven Version: apache maven 3.3.9
Java version: 1.8.0_91, vendor: Oracle Corporation

**asciidoctor**
`        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>1.5.3</version>
`

**asciidoctorj-pdf**
`          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>1.5.0-alpha.11</version>
          </dependency>
`

**Error:**

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (rename-pdf) on project hbase: An Ant BuildException has occured: Warning: Could not find file /grid/0/jenkins/workspace/hbase/target/site/book.pdfmarks to copy.
[ERROR] around Ant part ...<move file="/grid/0/jenkins/workspace/hbase/target/site/book.pdfmarks" tofile="/grid/0/jenkins/workspace/hbase/target/site/apache_hbase_reference_guide.pdfmarks"/>... @ 5:166 in /grid/0/jenkins/workspace/hbase/target/antrun/build-rename file.xml

**Comment by abelsromero** [comment]
`.pdfmarks` is not generated by default since `asciidoctor-pdf.alpha.10` ([release notes](https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.5.0.alpha.10)).
If you need it*, you can generate it adding the attribute like in this example
```
    <attributes>
        <sourcedir>${project.build.sourceDirectory}</sourcedir>
        <pdfmarks/>
    </attributes>
```

\* However, I see that the error is caused by the ant plugin configuration that moves the file. I don't understand the build process, but maybe the file is no longer necessary and you can just skip the move line https://github.com/apache/hbase/blob/master/pom.xml#L1117.

**Comment by mojavelinux** [comment]
Please note that in Asciidoctor PDF 1.5.0.alpha.14, the name of the attribute is changing to pdfmark. I recommend setting both for now.

**Comment by saravankrish** [comment]
Thanks for your quick response. It worked.
