### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#575]
The [Travis CI builds for AsciidoctorJ](https://travis-ci.org/asciidoctor/asciidoctorj) stopped working recently (specifically the jdk7 jobs), presumably because of a change to the Travis infrastructure. These failures don't seem to be caused by the code. Unfortunately, the failures are blocking us from detecting regressions in core, so we need to get these fixed as soon as possible.

**Comment by robertpanzer** [comment]
Thanks for the pointer.
I'll look at it once I find the time.
But it looks really strange that the JAVA_HOME is pointing to an invalid path...

**Comment by mojavelinux** [comment]
As @abelsromero pointed it, it may be as simple as adding:

```
dist: precise
```

**Comment by abelsromero** [comment]
Facts, on September 7th TravisCI switched all builds to the new Trusty Ubuntu image that changes these:
* oraclejdk7 and any jdk6 are NOT available in new images. Only openjdk7 & 8, and oraclejdk8
* There's an issue with the gradle ssl certificate validation using java7. I hope they'll fix it at some point. Right now can be fixed with this https://github.com/uber-java/tally/blob/2cea75ecc2f896dfd5e32b94bff71f211c8bde56/ci/before_install.sh#L6-L12. I have validated this in this branch https://github.com/abelsromero/asciidoctorj/blob/fix/update_travisci_to_trusty/.travis.yml#L14-L20.
* Once fixed the gradle ssl issue, test against upstream master fail. Some other mysterious stuff that causes this https://github.com/jruby-gradle/jruby-gradle-plugin/issues/305. I am thinking of asking the TravisCI team what they know, maybe they do something with the .m2 folder that corrupts some files. I tried to reproduce this locally modifying the file and everything worked or produced different error messages.

So, the only thing that I found that allows to keep working as now (full build, test +upstream asciidoctor/master test) is using the precise config. TravisCI will support precise until [1st April 2018](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status), we have some time.

**Comment by mojavelinux** [comment]
Thanks for this detailed information @abelsromero!

**Comment by abelsromero** [comment]
PR https://github.com/asciidoctor/asciidoctorj/pull/576.
Shouldn't it appear automatically based on the title?

**Comment by mojavelinux** [comment]
:+1:

**Comment by abelsromero** [comment]
I just saw a failing test on the 1.6.0 branch, which remind me that needs to be fixed also. @robertpanzer do you need me to send a PR for that or do you manage that with a cherrypick?

**Comment by robertpanzer** [comment]
Thanks for the pointer @abelsromero 
Just cherry-picked your commit from master.
