### ISSUE TITLE
(NoMethodError) undefined method `empty?' for nil:NilClass on DescriptionListEntry.getDescription().getText()

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#607]
Take the asciidoctor example presented in the user manual ([Labeled List](http://asciidoctor.org/docs/user-manual/#labeled-list) Section):

```
Dairy::
* Milk
* Eggs
Bakery::
* Bread
Produce::
* Bananas
```

If you load the first `DescriptionListEntry`, and then its description, the `ListItem` object is not null: `org.asciidoctor.ast.impl.ListItemImpl@51c65a43`

But when you call `getText()` on that object, you get this exception:

```
Exception in thread "main" org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `empty?' for nil:NilClass
	at RUBY.apply_subs(uri:classloader:/gems/asciidoctor-1.5.6.1/lib/asciidoctor/substitutors.rb:85)
	at RUBY.text(uri:classloader:/gems/asciidoctor-1.5.6.1/lib/asciidoctor/list.rb:76)
```

Java code to reproduce the problem:
```
String s = "Dairy::\n" +
        "* Milk\n" +
        "* Eggs\n" +
        "Bakery::\n" +
        "* Bread\n" +
        "Produce::\n" +
        "* Bananas";

Asciidoctor asciidoctor = org.asciidoctor.Asciidoctor.Factory.create();
Document document = asciidoctor.load(s, new java.util.HashMap<String, Object>());
DescriptionList descriptionList = (DescriptionList) document.getBlocks().get(0);
DescriptionListEntry descriptionListEntry = descriptionList.getItems().get(0);
ListItem description = descriptionListEntry.getDescription();
description.getText();
```

Tested with Version `1.6.0-alpha.6`

---

Maybe this is the same problem as #593

**Comment by jmini** [comment]
I have tried it with the lattest `1.6.0-SNAPSHOT` version (see https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0#using-a-snapshot-version)

I think I got the same error with `asciidoctorj-1.6.0-20171229.071751-239.jar`.

I have no idea how I can debug it...

**Comment by robertpanzer** [comment]
Hmm... I thought I responded yesterday, but apparently this got lost.
The same method would fail with the same error in Asciidoctor Ruby.
There is a separate method `ListItem.hasText()` that you can call before to check if the ListItem has a text. Because in this case the ListItem will have a nested block.

What would you expect for ListItem.getText() to behave when it doesn't have text but blocks.
The Ruby implementation throws an error.
Should we protect against this error and return sth else or throw another exception type?

**Comment by jmini** [comment]
Thank you for your answer. If the ruby implementation throws an exception, I do not think that the Java Bridge should do something else.

Maybe the Javadoc of `getText()` could mention this explicitly:

    /**
     * @return The text of the cell including substitutions being applied.
     * @throws Exception if no text is set. Consider calling {@link #hasText()} before calling this method.
     */
    String getText();

(feedback welcomed)

---
For my code, I will gard `listitem.getText()` calls with `if(listitem.hasText())`.

**Comment by robertpanzer** [comment]
This looks great!
Do you want to create a PR with this addition?

**Comment by jmini** [comment]
Pull request: #610

**Comment by mojavelinux** [comment]
At first I didn't believe it, but then I checked and you're right. If you call the `text` method (i.e., `getText()`) on a description item that only has blocks, an exception is thrown. The built-in html converter happens to always check `text?` (i.e., `hasText()`) first.

This was actually due to a recent optimization. I was looking for places where text was nil, but I missed this one. I'm going to reconsider this behavior in core since it doesn't seem very nice.

**Comment by jmini** [comment]
> What would you expect for ListItem.getText() to behave when it doesn't have text but blocks.
The Ruby implementation throws an error.

From my point of view (user of the java API), I would expect `getText()` to return `null` if `hasText()` returns `false`.

But as I told before, I think that the Java bridge should behave the same way than the ruby implementation.

> I'm going to reconsider this behavior in core since it doesn't seem very nice.

@mojavelinux if you optimize this, please let us know (in order to update the javadoc, and for my other experiments).

**Comment by mojavelinux** [comment]
Agreed. :+1:

**Comment by robertpanzer** [comment]
Behavior clarified in javadoc with #610 
Thanks, @jmini 🙌
