### ISSUE TITLE
Malformed rendering when using callouts within Monotree blocks

### ISSUE THREAD

**Issue by DamCx** [asciidoctor/asciidoctorj#691]
Hello,

I'm trying to use [Monotree](https://github.com/allati/asciidoctor-extension-monotree) in my asciidoc.

And during rendering, I have some issues about the fact that, when used with callouts, the overall page is quite malformed.

When looking into *Monotree*'s code, it sends a bunch of lines, containing, the tree, it then calls the `createBlock(StructuralNode, String, List<String>, Map<String, Object>, Map<Object, Object>)` method from the **BlockProcessor** class. It might have some bug in the rendering on that case.

Any idea/way how to solve this?

Thanks in advance

**Comment by mojavelinux** [comment]
I see you've filed a related issue in the repository for that project.

https://github.com/allati/asciidoctor-extension-monotree/issues/4

Since this is an issue with the extension and not with AsciidoctorJ, we should continue this conversation there.

**Comment by DamCx** [comment]
Well, I'm not sure this is entirely true, as I debbuged the execution of the *Monotree* project and the block was perfecty formatted.

But I'm sure we'll figure this out

**Comment by mojavelinux** [comment]
If you can show that AsciiDoc source text is not properly parsed and converted, then it's an issue with the processor (in this case, AsciidoctorJ). Otherwise, it has to be the extension because the processor itself doesn't create any nodes that aren't in the source document. My guess is that the extension is not creating the AST node correctly.

I've subscribed to the related thread. @robertpanzer could you subscribe as well? Please share the details in that issue of what you discovered when you debugged the execution and we can go from there.

**Comment by DamCx** [comment]
I've been trying to compare, on the same tree, the output of the execution of the extension.

The first output is without the callouts :
![withoutcallouts](https://user-images.githubusercontent.com/35628417/46935542-c164a500-d05b-11e8-8104-bfdaad839d6e.png)

The second output is with the callouts :
![withcallouts](https://user-images.githubusercontent.com/35628417/46935563-d17c8480-d05b-11e8-8867-fa54f83a55e4.png)

As you can see, the list to be generated by the extension are the same, except for the callouts prepared on my second attempt.

When rendering, the first tree is nicely formated. When it comes to the second tree, each line that includes a callout doesn't have its "new line" at the end. And as I previously indicated, the createBlock is directly taken from the Core's `BlockProcessor` class.

**Comment by robertpanzer** [comment]
@DamCx It would be great if you could create a reproducer.

**Comment by mojavelinux** [comment]
It's pretty clear that the extension is not processing the callouts. When an extension is applied to a block, that extension is responsible for handling all processing of that block. You no longer get any built-in behavior. Callout processing is built-in behavior. The monotree extension needs to handle these additional symbols. If it does not, they get passed through unprocessed, which is going to wreck HTML rendering because they contain HTML special characters (namely `<` and `>`).

**Comment by DamCx** [comment]
Yet, when it comes to the rendering, the lines are malformed and the callouts processed :

![results](https://user-images.githubusercontent.com/35628417/46942965-cd0d9700-d06e-11e8-8ee0-611135e4c120.png)

**Comment by mojavelinux** [comment]
Now I see what you are saying. If the listing block is created with the proper substitutions, then the callouts will be processed. And we can see that is true.

The fact that the glyphs are not rendering correctly is one of two things. One, the glpyhs are missing from the font the browser is using (which could explain the ???). The other is that the encoding of the string is not UTF-8 and thus substitions are mangling it (leading to a form of mojibake). Instead of passing raw glyphs, it might be better if the extension passed character references (though if the string is UTF-8 encoded, it should work fine).

**Comment by mojavelinux** [comment]
I just tried it using this fork of the monotree extension:

https://search.maven.org/artifact/org.incode.asciidoctor.monotree/incode-asciidoctor-extension-monotree/0.0.2/jar

The following snippet produces the correct result:

```
[monotree]
----
> A <1>
>> B
>>> C
>> D
>>> E
>>> F
----
<1> A
```

Can you try that version and see if it works for you. If it doesn't, then we know it is either a font or an encoding issue. Because from what I can see, AsciidoctorJ is doing the right thing.

**Comment by DamCx** [comment]
I'm trying it right now and I'll keep you updated

**Comment by DamCx** [comment]
The result is the same, so I'll have a closer look at the encoding of the string.

**Comment by mojavelinux** [comment]
I would also check to see if perhaps it's a missing font problem. View the source of the page and copy the relevant section into a fenced code block in this comment. If I see it and you don't (or it works in the GitHub comment) then you are simply missing the glyphs in the font that is being used. If what you paste includes ???, then it's more likely to be an encoding issue.

**Comment by DamCx** [comment]
I've been drilling down a bit more on this issue, as I hope to fix my problem.

I double-checked the `monotree` extension result and it is well formed, confirming the encoding problem @mojavelinux mentionned.

And from what I see, it could somehow be related to this issue : https://github.com/asciidoctor/asciidoctor/issues/673

As a matter of fact, I'm working on windows, and I'm currently on the 1.6.0-alpha.7 version of AsciidoctorJ.

When I'm debugging the execution, what I can see is that the core `asciidoctor` part takes as default encoding and default external encoding the system's one, which is `Windows-1252`.

Yet, my source files are all in `UTF-8`, and I need my output to be in `UTF-8` too. Does a config item exist so I can specify this ?

**Comment by mojavelinux** [comment]
> I can see is that the core asciidoctor part takes as default encoding and default external encoding the system's one, which is Windows-1252.

That's not correct. Asciidoctor force encodes all input to UTF-8 (unless it detects a BOM). Ruby (to my knowledge) respects this encoding when writing to the output file. However, there's indication that AsciidoctorJ is intercepting writing to the output stream and mangling the encoding, as reported in #541.

The workaround might be to pass `-Dfile.encoding=UTF-8` to the Java application.

@robertpanzer @abelsromero could this issue and #541 be the same?

**Comment by DamCx** [comment]
As you can see here, the values during debugging come from the RubyRuntime instance inside the JRubyAsciiDoctor class.

![rubyruntimedefaultencoding](https://user-images.githubusercontent.com/35628417/47068829-b2156100-d1ed-11e8-8ae6-63eef6f0fc7e.png)

This might be another hypothesis to work on. If you need more details, feel free to ask me.

**Comment by mojavelinux** [comment]
The difficult part here is reproducing this in a test. Once we're able to do that, it should be clear what change needs to happen in AsciidoctorJ, if any. But it would mean the tests have to run in an environment that does not use UTF-8.

(As an aside, absolutely hate that Windows does not default to UTF-8 in certain countries. There's just no reason for it).

**Comment by robertpanzer** [comment]
I am currently not aware that AsciidoctorJ intercepts the OutputStream unless you pass an OutputStream to the `to_file` option.
How is AsciidoctorJ invoked?

**Comment by mojavelinux** [comment]
> I am currently not aware that AsciidoctorJ intercepts the OutputStream unless you pass an OutputStream to the to_file option.

Thanks for clarifying that.

Here's what I'm trying to determine. Under what circumstances, if any, would AsciidoctorJ and/or JRuby take a UTF-8 string and write it to a file using a different encoding. Could this actually be a JRuby bug?

As far as I understand it, if I pass a UTF-8 encoding string to IO.write, Ruby will write that file using the encoding of the string. If that assumption is not true in JRuby, that could be our problem.

**Comment by mojavelinux** [comment]
Actually, I think I see the problem. I'm writing it up write now.

**Comment by mojavelinux** [comment]
Assume we have the following Ruby program named encoding-output-test.rb:

```ruby
str = 'é'
IO.write 'out.txt', str
```

Now we run this program using the following command:

```
ruby --encoding=WINDOWS-1252:WINDOWS-1252 encoding-output-test.rb
```

The file will be written with WINDOWS-1252 encoding. So my assumption that Ruby follows the encoding of the string when writing the file is not correct. It seems to be trying to coerce it.

What I can't understand, though, is how this is even working with the output of monotree. If I update encoding-output-test.rb to use one of the characters in question:

```
str = '├'
```

Then I get:

```
`write': U+251C to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252 (Encoding::UndefinedConversionError)
```

So how are we getting a file with mojibake if I can't get Ruby to write it in this simple program? We should be getting an exception.

**Comment by mojavelinux** [comment]
I will plan to update core to write files using UTF-8 encoding. But if that doesn't fix the problem, I'm at the point where I can only claim ignorance as to why this is not working. I understand the problem conceptually, but I simply cannot reproduce the conditions under which it happens.

**Comment by mojavelinux** [comment]
The workaround still stands, which is to change the system to use UTF-8 instead of Windows-1252. This workaround is mentioned in the Asciidoctor README. See https://github.com/asciidoctor/asciidoctor#requirements

**Comment by DamCx** [comment]
Thanks @mojavelinux for the info, I'll have a look at it.

**Comment by robertpanzer** [comment]
Would it help if I set the external encoding on the RubyInstanceConfig explicitly to UTF-8?
I currently don't touch it and JRuby seems to do some extra work specifically on Windows when determining the default encoding:
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/runtime/encoding/EncodingService.java#L71

**Comment by mojavelinux** [comment]
> Would it help if I set the external encoding on the RubyInstanceConfig explicitly to UTF-8?

I do believe that would help as we are forcing the encoding to UTF-8 anyway. But if that's not possible, it *should* work that as long as the input file is in UTF-8 and the output file is written using UTF-8, then it should stay in UTF-8 all the way through.

Note that this is going to improve substantially in Asciidoctor 2.0 since we will start reading (and writing) files with UTF-8 coercion turned on. We couldn't do this up to this point since that isn't supported in Ruby 1.8.7. So this might also be one of those, if we are just patient, this problem will go away by addressing it at the IO layer.

**Comment by DamCx** [comment]
Well, in my case, I don't have Asciidoctor, it is already packaged by AsciidoctorJ. I'll see if I can work this out.

**Comment by mojavelinux** [comment]
Yes, I understand. But it's possible to get AsciidoctorJ to use the gem from another path by setting the GEM_PATH. See https://github.com/asciidoctor/asciidoctorj#gem_path. This is most useful for testing such as in circumstances like this.

You could also open the jar and modify the document.rb file, then save it back to the jar file. (I'm not saying it's easy, just that it can be done).

**Comment by DamCx** [comment]
I modified the jar to reflect the changes on the `document.rb` file. Unfortunately, the files are still converted and saved in the system's encoding, which in my case isn't the good one.

**Comment by mojavelinux** [comment]
Can you verify it actually runs the modified line of code by adding a `puts "modified"` above the modified line?

If that doesn't work, I really don't know what else to do. It would mean JRuby just isn't doing what it's supposed to be doing. But I find that difficult to believe.

**Comment by mojavelinux** [comment]
Aha, I bet I know what it is and why it only happens when you use callout numbers.

The extension generates a string and uses it to create a block. Since your system encoding is WINDOWS-1252, that string goes into the Asciidoctor AST as WINDOWS-1252. Asciidoctor does not reencode strings that are added by an extension. If all Asciidoctor does is pass through that string unmodified, Ruby seems to be able to gracefully coerce it to match the rest of the output. But if that string is modified, as it is when callouts are processed, then Ruby mangles the string because of the mixed encodings.

So the problem is with the extension. The extension needs to make sure that any strings it creates are encoded as UTF-8. Otherwise, they won't be compatible with the rest of the strings in the Asciidoctor AST.

**Comment by mojavelinux** [comment]
It turns out Asciidoctor does normalize and reencode the lines of the block if passed as a string, but not if passed as an array. (I'm not sure that's the correct behavior, but just FYI).

**Comment by DamCx** [comment]
I forked the extension to check the string encoding, as it comes through an array of string. So I'm sure that what comes out of the extension is in the right encoding.

Yet, once the extension repackaged and my project updated, the final files are still saved as Windows-encoded files. And I'm sure it runs the `modified` build.

I don't have a clue why.

**Comment by mojavelinux** [comment]
I think I've finally got it. (No, really this time). Everything we've confirmed is that Asciidoctor, AsciidoctorJ, and the extension are doing what they are supposed to do. Which is fantastic. (Sorry for the false alarm @robertpanzer).

So where is the ??? coming from then?

It's so simple it's right in front of our eyes. Your system encoding is WINDOWS-1252. The characters that the monotree extension uses (box diagram glyphs) are simply not available in that codeset. So the *operating system* displays ??? instead of the actual character.

I was able to confirm this by changing my system locale to cp1252 (WINDOWS-1252) and view the generated file. When I do that, I see ??? instead of the box diagram glyphs. When I change my encoding back to UTF-8, then the exact same file displays correctly.

The workaround would be to modify the monotree extension to use glyphs that are available in the WINDOWS-1252 codeset. Or, you can change your system to UTF-8. But you simply can't view the glyphs as they currently are when your codeset is set to WINDOWS-1252. It's simply incompatible.

**Comment by mojavelinux** [comment]
> Since your system encoding is WINDOWS-1252, that string goes into the Asciidoctor AST as WINDOWS-1252.

I found out this is not true. Java always uses UTF-16 to store strings internally.

**Comment by mojavelinux** [comment]
In the monotree extension, print this just above the createBlock:

```
System.out.println(String.join("\n", tree));
```

You should see `???` in the terminal, which shows that the problem exists there. If you can figure out how to get that to not print `???`, then you've solved the problem (whether it means using different glyphs or some other solution).

**Comment by DamCx** [comment]
I already did this to check out the formatting, and it does print `???`.

Yet, I encoded the strings in the extensions as UTF-8, and it doesn't change a thing, as my console still prints the same (I use Git bash as console, and forced the encoding of the console as UTF-8)

**Comment by mojavelinux** [comment]
Your system is simply not able to display these characters using your current settings. That's the problem.

What I don't know is why the characters can't be displayed when the system encoding is set to WINDOWS-1252. But I'm sure this is the problem.

You should have the same problem viewing this page: http://www.fileformat.info/info/unicode/char/251C/browsertest.htm

**Comment by DamCx** [comment]
Not at all, it works perfectly fine

![browsertest](https://user-images.githubusercontent.com/35628417/47205794-3cdd9380-d387-11e8-80f2-bd19d8759e74.png)

**Comment by mojavelinux** [comment]
Well, I don't really know what to tell you. I've gone as far as I can go on this issue.

What I'm sure of is that you'll have to figure out how to get the strings that are passed to createBlock to print correctly in the terminal. Asciidoctor is just going to send those characters directly to the output, so they have to be right at that point.

**Comment by DamCx** [comment]
I was wondering if the `Document.convert()` method was doing its job right, as it might use the wrong encoding.

**Comment by mojavelinux** [comment]
I'm absolutely certain the problem is coming from the monotree extension. I have checked, doubled checked, and tripled checked how Asciidoctor is handling encoding and I'm confident it's doing the right thing.

**Comment by DamCx** [comment]
Yet, I don't understand why the files are in the end encoded as Windows-1252. I'll keep you posted if I can figure something out.

Thanks for your time.

**Comment by robertpanzer** [comment]
I see, you already ported it to 1.6. My bad.
But I tried the same and I got cp1252 in the defaultExternalEncoding and defaultFilesystemEncoding, but the result still looks ok to me.

I rendered this document:
```
= Test

Test

== Test

[tree]
----
> A <1>
>> B <2>
----
<1> Callout
```
 and I got this output, which should be ok, the symbols are rendered as `e2 94 94  e2 94 80 e2 94 80`.

```
00000340  6e 74 22 3e 0a 3c 70 72  65 3e 41 20 3c 62 20 63  |nt">.<pre>A <b c|
00000350  6c 61 73 73 3d 22 63 6f  6e 75 6d 22 3e 28 31 29  |lass="conum">(1)|
00000360  3c 2f 62 3e 0a e2 94 94  e2 94 80 e2 94 80 20 42  |</b>.......... B|
00000370  20 3c 62 20 63 6c 61 73  73 3d 22 63 6f 6e 75 6d  | <b class="conum|
```

So I have to give up for today.

**Comment by mojavelinux** [comment]
Thanks for doing this research, Robert! What we're learning is valuable no
matter the outcome.

**Comment by robertpanzer** [comment]
Definitely, I learned a lot today :) For example how fast it is to spin up a Windows VM on a Mac.

I probably have overseen sth or made sth different, but it would be good to know how the actual code with the problem looks like, and how it is executed.

**Comment by DamCx** [comment]
Thanks for the reseach,

I'll keep up digging on this as I really need to make it work. I'll also try and see if I have the same result on my CI platform, as it runs on CentOs.

I'll keep you both updated
