### ISSUE TITLE
Gradle bintrayUpload not able to upload distribution

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#861]
I was trying to make a release of AsciidoctorJ 2.2.0.
However the upload of asciidoctorj-distribution fails because it tries to upload jars from the libs/ directory created by this project, even though it only creates a zip and a tar in the distributions directory with the distribution plugin:
```
> Task :asciidoctorj-distribution:bintrayUpload FAILED
Caching disabled for task ':asciidoctorj-distribution:bintrayUpload' because:
  Build cache is disabled
Task ':asciidoctorj-distribution:bintrayUpload' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Gradle Bintray Plugin version: 1.8.4
:asciidoctorj-distribution:bintrayUpload: file /Users/robertpanzer/dev/asciidoctorj/asciidoctorj-distribution/build/libs/asciidoctorj-2.2.0-bin.jar.asc could not be found.
maven plugin was not applied, no pom will be uploaded.
:asciidoctorj-distribution:bintrayUpload: file /Users/robertpanzer/dev/asciidoctorj/asciidoctorj-distribution/build/libs/asciidoctorj-2.2.0-bin.jar.asc could not be found.
:asciidoctorj-distribution:bintrayUpload (Thread[Daemon worker Thread 10,5,main]) completed. Took 0.003 secs.
:bintrayPublish (Thread[Daemon worker Thread 10,5,main]) started.
```

@Fiouz Do you maybe have an idea what could be going on here?

**Comment by Fiouz** [comment]
I am not familiar with the [Bintray plugin](https://github.com/bintray/gradle-bintray-plugin), but could you please confirm that the following error message also appear:

```
Execution failed for task ':asciidoctorj-distribution:bintrayUpload'.
> No such property: toSignArtifact for class: org.gradle.plugins.signing.Signature
```

If it does, the failure may not be directly related to the non-existent `.jar` file but rather due to an incompatibility between the gradle-bintray-plugin and Gradle 5.x:

- **gradle-bintray-plugin** [makes use](https://github.com/bintray/gradle-bintray-plugin/blob/1.8.4/src/main/groovy/com/jfrog/bintray/gradle/tasks/BintrayUploadTask.groovy#L514) of the `Signature.getToSignArtifact()` method
- That method was [deprecated](https://github.com/gradle/gradle/commit/328d6f17ba4a9b2533a059428764432c5996e68a#diff-e0060c608f1a7ea3408d12e69968724bR380) in [Gradle 4.8](https://docs.gradle.org/4.8/release-notes.html#method-on-signature)
- That method was later [removed in Gradle 5.0](https://docs.gradle.org/5.0/release-notes.html#potential-breaking-changes)

**Comment by Fiouz** [comment]
Could you please try https://github.com/Fiouz/asciidoctorj/commit/d13e7bf4d9adafcdc863b41274b8d22fc5000686 to see if the same failure happen?

I used the following line in `asciidoctorj-distribution/gradle.properties` to avoid actual upload:
```
dryRun=true
```
(or use dummy credentials)

I would not call it a proper fix since it relies on Groovy meta-programming modifying the Gradle API for Groovy call sites.

**Comment by robertpanzer** [comment]
Yes, you are right, I have totally overseen this error as it only appeared at the end of the output, but not within the log of the task execution itself:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctorj-distribution:bintrayUpload'.
> No such property: toSignArtifact for class: org.gradle.plugins.signing.Signature
```

**Comment by robertpanzer** [comment]
@Fiouz Thank you! Your fix seems to work indeed! 🥇 
Could you please create a PR with this?

**Comment by abelsromero** [comment]
I think we can close this?

**Comment by robertpanzer** [comment]
Yes, bintray is history
