### ISSUE TITLE
Updating from 1.5.3 to 2.2.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [asciidoctor/asciidoctorj#886]
When I try to upgrade asciidoctorj from 1.5.3 to version after 1.5.7. The following code breaks.
```
public class ConcordionNullMacro extends InlineMacroProcessor {

    public ConcordionNullMacro(String macroName, Map<String, Object> config) {
        super(macroName, config);
    }

    @Override
    protected Object process(AbstractBlock parent, String target, Map<String, Object> attributes) {
        return CommandType.commandForName(target).process(attributes);
    }
}

```

The code should pass, but it throws an error:
```
ConcordionNullMacro.java:[16,22] process(AbstractBlock,java.lang.String,java.util.Map<java.lang.String,java.lang.Object>) in org.concordion.jtechlog.asciidoc.nullmacro.ConcordionNullMacro cannot override process(T,java.lang.String,java.util.Map<java.lang.String,java.lang.Object>) in org.asciidoctor.extension.MacroProcessor
[ERROR] attempting to assign weaker access privileges; was public
```

**Comment by robertpanzer** [comment]
Could you please clarify your issue?
The title mentions a change to 2.2.0, the description mentions 1.5.7.

**Comment by robertpanzer** [comment]
That said, 2.0.0 is really the version from which we want to start following the rules of semantic versioning. 
If sth like this hit you between 1.5.3 and 1.5.7 that’s honestly sad, but I am reluctant to release anything 1.5.x right now.

**Comment by SElab2019** [comment]
> That said, 2.0.0 is really the version from which we want to start following the rules of semantic versioning.
> If sth like this hit you between 1.5.3 and 1.5.7 that’s honestly sad, but I am reluctant to release anything 1.5.x right now.

Thanks for your quick replying. 

Yes. I was trying to upgrade asciidoctorj to the latest version 2.2.0 and my code breaks. Then I went to check which version of this backwards incompatibility issue starts. It starts from version 1.5.7.

**Comment by robertpanzer** [comment]
That change was necessary to allow running with JRuby 9.1.14.0.
Please check #624 and #625 

So there was a trade off for this change, and I think it made more sense to change the visibility to public – which it should have had in the first place – and allow running with the latest JRuby versions instead of keeping the strange visibility of this method.

**Comment by SElab2019** [comment]
Alright. That makes sense. Would it be better to add a breaking announcement in the release note? Then all other developers who use asciidoctorj can know it.

**Comment by robertpanzer** [comment]
You are completely right!
The 1.5.x releases always stayed in sync with Asciidoctor Core, so from that perspective it had to be named 1.5.7 because it packaged Asciidoctor Ruby 1.5.7.
Now that we do our best to follow Semantic Versioning since 2.2.0 this would definitely require an update of the major version.

Now this has happened and I hope we can leave that behind and do better in the future.

**Comment by robertpanzer** [comment]
Closing, as we won't or can't fix this.
We're definitely trying to avoid such situations in the future.
